server:
  port: 5005

googlePlacesApi:
  apiKey: AIzaSyDGt8FHoLLY1MwkWfQ556C9hyiMtLOlgEo
  placeAutocomplete:
    endpoint: https://maps.googleapis.com/maps/api/place/autocomplete/json
  placeSearch:
    endpoint: https://maps.googleapis.com/maps/api/place/nearbysearch/json
  placeDetails:
    endpoint: https://maps.googleapis.com/maps/api/place/details/json


watsonCloudService:
  textToSpeech:
    username: ed54a35c-c2e2-430b-994f-4dbab60314b6
    password: i8iFAqdxfBFS
  speechToText:
    username: afc9e73c-acf9-40bb-873f-8c0c9db8978f
    password: MUai6xWLnp0M
  conversation:
    username: 12a93e8e-c5de-42f0-b136-15f9bcb69cb4
    password: IdJxGCqJaGuS
    workspaceId: c5859796-664f-4cbf-a30d-8e9e3732e182
  naturalLanguageClassifier:
    username: a83e4070-0c22-4f09-9dba-19a4ec327bc4
    password: D4s53H0ZBLvJ
    id:
      destinationChoiceClassifier: 1e0d8ex232-nlc-17207
      postUserReviewClassifier: ebd2f7x230-nlc-59868
      booleanClassifier: ebd15ex229-nlc-59975
      transportationMethodClassifier: ebd2f7x230-nlc-59789
      globalInstructionClassifier: ebd2f7x230-nlc-59802
  naturalLanguageUnderstanding:
    username: 2cac0e79-e8d3-47a4-b028-b2dbed61580e
    password: 5AG5O55zrVKr
  discovery:
    endPoint: https://gateway.watsonplatform.net/discovery/api/
    version: 2017-09-01
    username: 0b998145-d53a-4f03-9cf0-cde647aca4ed
    password: Sv63MMyNUF7U
    environmentId: 4f3bfd84-164e-4763-a7b5-b40381cfa401
    collections:
      columbus-OH-US:
        name: columbus-OH-US
        id: 3fa9d27c-f9a2-4c6b-9598-cac3705ddc60

destinationCategory:
  restaurant: sw_dest_category_restaurant

appContext:
  booleanClassification: sw_boolean_classification
  waitingForUserReview: sw_waiting_for_user_review
  waitingForDestination: sw_waiting_for_destination
  transportationMethodSelection: sw_trans_method_selection